### PR TITLE
Messaging Screen of Okni-Chat 

### PR DESCRIPTION
**Pull request by Zolusion**
Adding base HTML & CSS codes, but CSS uses framework.

### CODE REVIEW

**Comment by Neodevils** [comment]
@Zolusion are we planning to use CSS frameworks?

I thought we will be using raw CSS.

**Review by Neodevils — CHANGES_REQUESTED** [review]
As I said earlier, for improving our skills, we should use raw CSS instead using CSS frameworks.

**Comment by Neodevils** [comment]
@Ivndjss, I think we still should wait for it.

**Comment by Ivndjss** [comment]
> @Ivndjss, I think we still should wait for it.

Noted. Mention me when it is ready

**Comment by Neodevils** [comment]
> > @Ivndjss, I think we still should wait for it.
> 
> Noted. Mention me when it is ready

Alright. 👌🏻

**Review by Neodevils — CHANGES_REQUESTED** [review]
Please move all images to assets folder.

**Review by Neodevils — APPROVED** [review]
ALGTM!

**Review by Ivndjss — COMMENTED** [review]
nothing to change

**Pull request merged**
